import mongoose from "mongoose";

const shopSchema = mongoose.Schema({
  ownerName: String,
  phoneNo: Number,
  email: String,
  userName: String,
  passWord: String,
  selectedFile: String,
  latitude: Number,
  longitude: Number,
  city: String,
  shopName: String,
  address: String,
  description: String,
  shopType: String,
  image1: String,
  item1: String,
  price1: Number,
  image2: String,
  item2: String,
  price2: Number,
  image3: String,
  item3: String,
  price3: Number,
  image4: String,
  item4: String,
  price4: Number,
  image5: String,
  item5: String,
  price5: Number,
  image6: String,
  item6: String,
  price6: Number,
  image7: String,
  item7: String,
  price7: Number,
  image8: String,
  item8: String,
  price8: Number,
  image9: String,
  item9: String,
  price9: Number,
  image10: String,
  item10: String,
  price10: Number,
  image11: String,
  item11: String,
  price11: Number,
  image12: String,
  item12: String,
  price12: Number,
  image12: String,
  item12: String,
  price12: Number,
  image13: String,
  item13: String,
  price13: Number,
  image14: String,
  item14: String,
  price14: Number,
  image15: String,
  item15: String,
  price15: Number,
  image16: String,
  item16: String,
  price16: Number,
  image17: String,
  item17: String,
  price17: Number,
  image18: String,
  item18: String,
  price18: Number,
  image19: String,
  item19: String,
  price19: Number,
  image20: String,
  item20: String,
  price20: Number,
});

const ShopSchema = mongoose.model("ShopSchema", shopSchema);

export default ShopSchema;
